#!/bin/bash
# Full Ubuntu VPS setup for Pro-Enroll API (98.93.105.128)
# Run on the server after uploading code:
#   cd /var/www/html/pro_enroll_api && sudo bash deploy/ubuntu-setup.sh

set -euo pipefail

API_ROOT="/var/www/html/pro_enroll_api"
APACHE_CONF="/etc/apache2/conf-available/pro-enroll.conf"

echo "=========================================="
echo " Pro-Enroll API — Ubuntu server setup"
echo "=========================================="
echo "API root: $API_ROOT"
echo ""

if [ ! -d "$API_ROOT/public" ]; then
  echo "ERROR: $API_ROOT/public not found."
  echo "Upload the full pro_enroll_api folder to /var/www/html/ first."
  exit 1
fi

# --- 1. System packages (optional) ---
echo "[1/7] Checking PHP + Composer..."
if ! command -v php >/dev/null 2>&1; then
  echo "Installing PHP..."
  apt-get update -qq
  apt-get install -y php php-mysql php-mbstring php-xml php-curl unzip
fi
if ! command -v composer >/dev/null 2>&1; then
  echo "Installing Composer..."
  apt-get install -y composer || {
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  }
fi

# --- 2. Apache modules + site config ---
echo "[2/7] Apache: rewrite, headers, Alias + routing..."
a2enmod rewrite headers 2>/dev/null || true

cat > "$APACHE_CONF" << 'EOF'
# Pro-Enroll API — generated by deploy/ubuntu-setup.sh
RedirectMatch 301 ^/pro_enroll_api/public/(.*)$ /pro_enroll_api/$1

Alias /pro_enroll_api /var/www/html/pro_enroll_api/public

<Directory /var/www/html/pro_enroll_api/public>
    Options -Indexes +FollowSymLinks
    AllowOverride All
    DirectoryIndex index.php
    Require all granted

    RewriteEngine On
    RewriteCond %{HTTP:Authorization} ^(.+)$
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%1]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^ index.php [L]
</Directory>

<Directory /var/www/html/pro_enroll_api>
    Options -Indexes +FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
EOF

a2enconf pro-enroll 2>/dev/null || true

# --- 3. .env ---
echo "[3/7] Environment file..."
if [ ! -f "$API_ROOT/.env" ]; then
  if [ -f "$API_ROOT/.env.remote" ]; then
    cp "$API_ROOT/.env.remote" "$API_ROOT/.env"
    echo "  Created .env from .env.remote"
  else
    echo "  WARN: No .env — copy .env.remote to .env and edit DB_PASS"
  fi
fi

# Fix APP_URL if it incorrectly ends with /public
if [ -f "$API_ROOT/.env" ] && grep -q 'APP_URL=.*/public' "$API_ROOT/.env"; then
  sed -i 's|APP_URL=\(.*\)/public|APP_URL=\1|' "$API_ROOT/.env"
  echo "  Fixed APP_URL (removed /public suffix)"
fi

# JWT_SECRET required for OTP verify → JWT session
if [ -f "$API_ROOT/.env" ]; then
  if ! grep -qE '^JWT_SECRET=.+$' "$API_ROOT/.env"; then
    SECRET=$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p -c 64)
    if grep -q '^JWT_SECRET=' "$API_ROOT/.env"; then
      sed -i "s|^JWT_SECRET=.*|JWT_SECRET=$SECRET|" "$API_ROOT/.env"
    else
      printf '\nJWT_SECRET=%s\n' "$SECRET" >> "$API_ROOT/.env"
    fi
    echo "  Generated JWT_SECRET in .env"
  fi
fi

# --- 4. Composer ---
echo "[4/7] Composer install + autoload classmap..."
cd "$API_ROOT"
composer install --no-dev --optimize-autoloader
composer dump-autoload -o

# --- 5. Permissions ---
echo "[5/7] File permissions..."
chown -R www-data:www-data "$API_ROOT/storage" 2>/dev/null || true
find "$API_ROOT/public" -type d -exec chmod 755 {} \;
find "$API_ROOT/public" -type f -exec chmod 644 {} \;

# --- 6. Reload Apache ---
echo "[6/7] Reload Apache..."
apache2ctl configtest
systemctl reload apache2

# --- 7. Smoke test ---
echo "[7/7] Smoke test (localhost)..."
echo ""
PING=$(curl -s -o /tmp/pe_ping.json -w "%{http_code}" http://127.0.0.1/pro_enroll_api/ping.php || true)
SPLASH=$(curl -s -o /tmp/pe_splash.json -w "%{http_code}" http://127.0.0.1/pro_enroll_api/v1/screens/splash || true)
AUTH=$(curl -s -o /tmp/pe_auth.json -w "%{http_code}" \
  -H "Authorization: Bearer smoke-test-token" \
  http://127.0.0.1/pro_enroll_api/v1/auth/me || true)

echo "  ping.php          HTTP $PING"
if [ -f /tmp/pe_ping.json ]; then
  grep -o '"ok":[^,]*' /tmp/pe_ping.json 2>/dev/null || head -c 200 /tmp/pe_ping.json
  echo ""
fi
echo "  v1/screens/splash HTTP $SPLASH"
if [ -f /tmp/pe_splash.json ]; then
  head -c 200 /tmp/pe_splash.json
  echo ""
fi
echo "  auth/me + Bearer  HTTP $AUTH (expect 401 invalid_token, NOT missing_token)"
if [ -f /tmp/pe_auth.json ]; then
  grep -o '"code":"[^"]*"' /tmp/pe_auth.json 2>/dev/null || head -c 120 /tmp/pe_auth.json
  echo ""
fi

echo ""
echo "=========================================="
if [ "$PING" = "200" ] && [ "$SPLASH" = "200" ]; then
  echo " SUCCESS — API is live"
else
  echo " PARTIAL — check output above"
  echo " If db FAIL: import database/setup_mysql_user.sql in phpMyAdmin"
  echo " If class not found: composer dump-autoload -o"
  echo " Apache log: tail -20 /var/log/apache2/error.log"
fi
echo "=========================================="
echo ""
echo "Postman base_url: http://98.93.105.128/pro_enroll_api"
echo "Ping:             http://98.93.105.128/pro_enroll_api/ping.php"
echo "Splash:           http://98.93.105.128/pro_enroll_api/v1/screens/splash"
